services:
  postgres:
    image: 'postgres:18.2'
    environment:
      POSTGRES_DB: cloud-storage-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d cloud-storage-db" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  minio:
    image: 'minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1'
    entrypoint: /bin/sh -c 'export MINIO_ROOT_PASSWORD=$$(cat /run/secrets/minio_password) && minio server /data --console-address ":9001"'
    environment:
      MINIO_ROOT_USER: minioadmin
    secrets:
      - minio_password
    volumes:
      - minio_data:/data
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  backend:
    image: eclipse-temurin:25-jre
    working_dir: /app
    volumes:
      - ./backend/build/libs:/app/libs:ro
    entrypoint: ["java", "-jar", "/app/libs/cloud-file-storage-0.0.1-SNAPSHOT.jar", "--spring.profiles.active=dev"]
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cloud-storage-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_CONFIG_IMPORT: "optional:configtree:/run/secrets/"
      MINIO_URL: http://minio:9000
      MINIO_ACCESS_NAME: minioadmin
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    secrets:
      - source: db_password
        target: spring.datasource.password
      - source: minio_password
        target: minio.access.secret
      - source: redis_password
        target: spring.data.redis.password
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  redis:
    image: redis:8-alpine
    command: sh -c "redis-server --requirepass $$(cat /run/secrets/redis_password)"
    secrets:
      - redis_password
    ports:
      - "127.0.0.1:6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

secrets:
  db_password:
    file: backend/secrets/db_password.txt
  minio_password:
    file: backend/secrets/minio_password
  redis_password:
    file: backend/secrets/redis_password

volumes:
  postgres_data:
  minio_data: