services:
  backend:
    build: .
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cloud-storage-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_CONFIG_IMPORT: "optional:configtree:/run/secrets/"
    secrets:
      - source: spring_datasource_password
        target: spring.datasource.password
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: 'postgres:18.2'
    environment:
      POSTGRES_DB: cloud-storage-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d cloud-storage-db" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    restart: unless-stopped

secrets:
  db_password:
    file: backend/secrets/db_password.txt
  spring_datasource_password:
    file: backend/secrets/spring.datasource.password

volumes:
  postgres_data: