spring:
  application:
    name: cloud-file-storage

---
#dev profile
spring:
  config:
    activate:
      on-profile: dev
    import: "optional:configtree:./secrets/"
  docker:
    compose:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/cloud-storage-db
    username: postgres
    password: ${spring.datasource.password}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true
  security:
    user:
      name: dev
      password: dev123
      roles: ADMIN