spring:
  application:
    name: cloud-file-storage
  docker:
    compose:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true
  session:
    redis:
      namespace: spring:session
  data:
    redis:
      port: 6379
      password:
      host: redis
  datasource:
    username: postgres
    password:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
server:
  tomcat:
    max-part-count: 100
minio:
  access:
    name: minioadmin
    secret:
  bucket:
    name: user-files
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true